# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# Site settings
title: SCENEE
author: SCENEE
email: contact@scenee.com
avatar: profile.jpg

description: | #> # this means to ignore newlines until "baseurl:"
  Welcom! I'm Scenee[/siÀêni/]. Software Development Engineer.
  My goal is to create incredible products in my short life.
  I love Unix philosophy, Linux and C. Also iOS, ObjC and Swift.
  Recently I have been intersted in wireless technologies(i.e. BLE)
  and functional programming(i.e. Swift, Erlang)

url: http://scenee.github.io/  # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

twitter: scenee
github:  scenee
stackoverflow: users/5097257/scenee

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# needed for travis-ci build
exclude: [vendor]
